[package]
name = "cascade"
version = "1.0.0"
authors = ["Jackson Lewis <inquisitivepenguin@protonmail.com>"]
description = "Dart-like cascade macro for Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/inquisitivepenguin/cascade"

[dependencies]
